/*dados gerados pelo chatGPT*/

INSERT INTO ss_midia (titulo, artista, duracao, genero, tipo_midia) VALUES
# músicas (1-20)
('Back in Black', 'AC/DC', 255, 'ROCK', 'MUSICA'),
('Shape of You', 'Ed Sheeran', 263, 'POP', 'MUSICA'),
('Garota de Ipanema', 'Tom Jobim', 192, 'MPB', 'MUSICA'),
('Take Five', 'Dave Brubeck', 324, 'JAZZ', 'MUSICA'),
('Symphony No.5', 'Beethoven', 441, 'CLASSICA', 'MUSICA'),
('Bohemian Rhapsody', 'Queen', 354, 'ROCK', 'MUSICA'),
('Thriller', 'Michael Jackson', 312, 'POP', 'MUSICA'),
('Aquarela', 'Toquinho', 270, 'MPB', 'MUSICA'),
('So What', 'Miles Davis', 545, 'JAZZ', 'MUSICA'),
('Canon in D', 'Pachelbel', 360, 'CLASSICA', 'MUSICA'),
('Smells Like Teen Spirit', 'Nirvana', 301, 'ROCK', 'MUSICA'),
('Bad Romance', 'Lady Gaga', 295, 'POP', 'MUSICA'),
('Trem das Onze', 'Adoniran Barbosa', 210, 'MPB', 'MUSICA'),
('Fly Me to the Moon', 'Frank Sinatra', 150, 'JAZZ', 'MUSICA'),
('Clair de Lune', 'Claude Debussy', 312, 'CLASSICA', 'MUSICA'),
('Hotel California', 'Eagles', 390, 'ROCK', 'MUSICA'),
('Levitating', 'Dua Lipa', 203, 'POP', 'MUSICA'),
('Águas de Março', 'Elis Regina', 241, 'MPB', 'MUSICA'),
('My Favorite Things', 'John Coltrane', 426, 'JAZZ', 'MUSICA'),
('Swan Lake', 'Tchaikovsky', 355, 'CLASSICA', 'MUSICA'),
# audiobooks (21-40)
('1984', 'George Orwell', 660, 'FICCAO', 'AUDIOBOOK'),
('O Poder do Hábito', 'Charles Duhigg', 420, 'BIOGRAFIA', 'AUDIOBOOK'),
('O Hobbit', 'J.R.R. Tolkien', 720, 'FICCAO', 'AUDIOBOOK'),
('Steve Jobs', 'Walter Isaacson', 900, 'BIOGRAFIA', 'AUDIOBOOK'),
('Fahrenheit 451', 'Ray Bradbury', 480, 'FICCAO', 'AUDIOBOOK'),
('Elon Musk', 'Ashlee Vance', 750, 'BIOGRAFIA', 'AUDIOBOOK'),
('Duna', 'Frank Herbert', 900, 'FICCAO', 'AUDIOBOOK'),
('Becoming', 'Michelle Obama', 840, 'BIOGRAFIA', 'AUDIOBOOK'),
('Neuromancer', 'William Gibson', 600, 'FICCAO', 'AUDIOBOOK'),
('Alexander Hamilton', 'Ron Chernow', 870, 'BIOGRAFIA', 'AUDIOBOOK'),
('O Guia do Mochileiro das Galáxias', 'Douglas Adams', 360, 'FICCAO', 'AUDIOBOOK'),
('Leonardo da Vinci', 'Walter Isaacson', 960, 'BIOGRAFIA', 'AUDIOBOOK'),
('Jogador Número 1', 'Ernest Cline', 700, 'FICCAO', 'AUDIOBOOK'),
('Malala Yousafzai', 'Malala Yousafzai', 400, 'BIOGRAFIA', 'AUDIOBOOK'),
('A Máquina do Tempo', 'H.G. Wells', 420, 'FICCAO', 'AUDIOBOOK'),
('Benjamin Franklin', 'Walter Isaacson', 800, 'BIOGRAFIA', 'AUDIOBOOK'),
('O Conto da Aia', 'Margaret Atwood', 540, 'FICCAO', 'AUDIOBOOK'),
('Mahatma Gandhi', 'Louis Fischer', 660, 'BIOGRAFIA', 'AUDIOBOOK'),
('Crônicas Marcianas', 'Ray Bradbury', 450, 'FICCAO', 'AUDIOBOOK'),
('Nelson Mandela', 'Anthony Sampson', 780, 'BIOGRAFIA', 'AUDIOBOOK'),
# podcasts (41-60)
('Tech Talks Daily', 'Neil C. Hughes', 45, 'TECH', 'PODCAST'),
('The Vergecast', 'The Verge', 60, 'TECH', 'PODCAST'),
('Reply All', 'Gimlet Media', 55, 'TECH', 'PODCAST'),
('Waveform: The MKBHD Podcast', 'Marques Brownlee', 50, 'TECH', 'PODCAST'),
('Clockwise', 'Relay FM', 30, 'TECH', 'PODCAST'),
('TED Talks Technology', 'TED', 18, 'TECH', 'PODCAST'),
('Accidental Tech Podcast', 'Marco Arment', 90, 'TECH', 'PODCAST'),
('The Daily Tech News Show', 'Tom Merritt', 60, 'TECH', 'PODCAST'),
('The CultCast', 'Cult of Mac', 40, 'TECH', 'PODCAST'),
('Techmeme Ride Home', 'Techmeme', 20, 'TECH', 'PODCAST'),
('The Joe Rogan Experience', 'Joe Rogan', 180, 'ENTRETENIMENTO', 'PODCAST'),
('My Favorite Murder', 'Karen Kilgariff & Georgia Hardstark', 75, 'ENTRETENIMENTO', 'PODCAST'),
('The Daily Show with Trevor Noah', 'Comedy Central', 50, 'ENTRETENIMENTO', 'PODCAST'),
('The Michelle Obama Podcast', 'Michelle Obama', 60, 'ENTRETENIMENTO', 'PODCAST'),
('Armchair Expert', 'Dax Shepard', 90, 'ENTRETENIMENTO', 'PODCAST'),
('Stuff You Should Know', 'iHeartRadio', 50, 'ENTRETENIMENTO', 'PODCAST'),
('The Moth', 'The Moth', 45, 'ENTRETENIMENTO', 'PODCAST'),
('Wait Wait... Don’t Tell Me!', 'NPR', 60, 'ENTRETENIMENTO', 'PODCAST'),
('How Did This Get Made?', 'Paul Scheer', 70, 'ENTRETENIMENTO', 'PODCAST'),
('No Such Thing As A Fish', 'QI', 40, 'ENTRETENIMENTO', 'PODCAST');



